version: '3'
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 88:88
      - 3000:3000
    environment:
      - PUID=998
      - PGID=100
    volumes:
      - /var/lib/docker/volumes/adguard_work/_data:/opt/adguardhome/work
      - /var/lib/docker/volumes/adguard_config/_data:/opt/adguardhome/conf
