version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/Oslo
      - PUID=1026
      - PGID=100
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=false
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=DS920+
    volumes:
      - /volume1/docker/tdarr/server:/app/server
      - /volume1/docker/tdarr/configs:/app/configs
      - /volume1/docker/tdarr/logs:/app/logs
      - /volume1/media_location:/media
      - /volume1/docker/tdarr/transcode_cache:/temp
    devices:
      - /dev/dri:/dev/dri


#######NODE########

{
  "nodeName": "Node",
  "serverIP": "192.168.1.x",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "/media",
      "node": "./location"
    },
    {
      "server": "/temp",
      "node": "\\\\docker\\tdarr\\transcode_cache"
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": "",
  "nodeIP": "192.168.1.x",
  "nodePort": "8267",
  "platform_arch": "win32_x64_docker_false"
}
